### PR TITLE
GU0073 Member of non-public type should be internal.

### PR DESCRIPTION
**Pull request by JohanLarsson**

### CODE REVIEW

**Comment by JohanLarsson** [comment]
Guess we can add test cases for doing new and changing accessibility. It will work but always nice with tests.

**Comment by AArnott** [comment]
You have some placeholders in the documentation though

**Comment by JohanLarsson** [comment]
@AArnott chances are there are only placeholders in the entire documentation. I generate them but don't write much.
This analyzer lib is just a bag of stuff.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/Gu.Analyzers/1.5.4-dev
Published it so we can use it while waiting for stylecop.

**Pull request merged**
